spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-1
          uri: http://localhost:8081/
          predicates:
            - Path=/first-service/**
        - id: user-service-2
          uri: http://localhost:8082/
          predicates:
            - Path=/second-service/**
