spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service-1
          uri: lb://USER-SERVICE-1
          predicates:
            - Path=/first-service/**
          filters:
            # - AddRequestHeader=gateway-request, first-service-request2
            # - AddResponseHeader=gateway-response, first-service-response2
            - CustomFilter
        - id: user-service-2
          uri: lb://USER-SERVICE-2
          predicates:
            - Path=/second-service/**
          filters:
            # - AddRequestHeader=gateway-request, second-service-request2
            # - AddResponseHeader=gateway-response, second-service-response2
            - CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Logging Filter
                preLogger: true
                postLogger: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
